<a href="https://colab.research.google.com/github/DAVIDnHANG/DS-Unit-2-Regression-Classification/blob/master/module4/module4_workALong_Reg%26class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Do not use linear regresseion on classificatiohn of 5+

# import files

In [0]:
import os, sys
in_colab = 'google.colab' in sys.modules

# If you're in Colab...
if in_colab:
    # Pull files from Github repo
    os.chdir('/content')
    !git init .
    !git remote add origin https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification.git
    !git pull origin master
    
    # Install required python packages
    !pip install -r requirements.txt
    
    # Change into directory for module
    os.chdir('module4')

Initialized empty Git repository in /content/.git/
remote: Enumerating objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0), pack-reused 156
Receiving objects: 100% (156/156), 19.30 MiB | 15.10 MiB/s, done.
Resolving deltas: 100% (71/71), done.
From https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
     |████████████████████████████████| 92kB 5.0MB/s 
     |████████████████████████████████| 112kB 16.1MB/s 
     |████████████████████████████████| 133kB 46.2MB/s 
     |████████████████████████████████| 57.7MB 530kB/s 
     |████████████████████████████████| 235kB 42.0MB/s 
     |████████████████████████████████| 614kB 40.3MB/s 
     |████████████████████████████████| 235kB 40.8MB/s 
     |████████████████████████████████| 307kB 42.0MB/s 
     |████████████████████████████████| 51kB 17.5MB/s 
     |████████████████████████████████| 215kB 40.9MB/s 
     |█████████

In [0]:
import pandas as pd
train = pd.read_csv('../data/titanic/train.csv')
test = pd.read_csv('../data/titanic/test.csv')
train.shape, test.shape


((891, 12), (418, 11))

train split


In [0]:
set(train.columns) - set(test.columns)

{'Survived'}

# train split

In [0]:
from sklearn.model_selection import train_test_split

split_train, split_val = train_test_split(train, random_state=42)
split_train.shape, split_val.shape


((668, 12), (223, 12))

In [0]:
split_train.describe()
split_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# follow along
split_train
split_val

In [0]:
target = 'Survived'
y_train = split_train[target]
y_train.value_counts(normalize=True)

0    0.621257
1    0.378743
Name: Survived, dtype: float64

In [0]:
#what if we guessed the majority of class for evey prediction
majority_class = y_train.mode()[0]
y_pred = [majority_class]*len(y_train)

sum(abs(y_pred-y_train)) / len(y_train)

0.3787425149700599

# classification accuracy score

A baseline for classification can be the most common class in the training dataset.

A baseline for regression can be the mean of the training labels. 

A baseline for time-series regressions can be the value from the previous timestep.

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_pred)

0.6212574850299402

In [0]:
y_val = split_val[target]
y_pred = [majority_class] * len(y_val)
accuracy_score(y_pred,y_val)

0.600896860986547

# regression model 5 step

In [0]:
pip install -U scikit-learn

Requirement already up-to-date: scikit-learn in /usr/local/lib/python3.6/dist-packages (0.21.3)


In [0]:

#1. import estimator class
from sklearn.linear_model import LinearRegression

#2 Instantiate this class
linear_reg = LinearRegression()
#3 
features = ['Pclass','Age','Fare']
X_train = split_train[features]
X_val = split_train[features]

#3 A
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)
#4fit the model
linear_reg.fit(X_train_imputed, y_train)

#5 apply the model to new data
#the predictions look like this
linear_reg.predict(X_val_imputed)



array([ 0.63798671,  0.25700854,  0.46549198,  0.27761056,  0.93261982,
        0.47524865,  0.25101671,  0.40366468,  0.89142179,  0.22782825,
        0.2273864 ,  0.22860242,  0.27782622,  0.46059181,  0.3065164 ,
        0.72043678,  0.24143951,  0.29143245,  0.35403316,  0.22738283,
        0.29204757,  0.19251405,  0.23888456,  0.22808277,  0.27119451,
        0.27738081,  0.48593766,  0.22794018,  0.39107122,  0.22782825,
        0.27736316,  0.58691912,  0.24347653,  0.27805953,  0.53293576,
        0.38128803,  0.44157768,  0.79066301,  0.56382127,  0.35647227,
        0.24490821,  0.61211033,  0.39504194,  0.31225015,  0.64420711,
        0.85275165,  0.22795194,  0.42209349,  0.39592303,  0.34751106,
        0.68453849,  0.42832139,  0.23092017,  0.30520841,  0.42945022,
        0.64167985,  0.36320646,  0.25164241,  0.29067951,  0.72549978,
        0.08940663,  0.47268923,  0.44631905,  0.22793786,  0.24114822,
        0.61666672,  0.40189091,  0.29792275,  0.15322242,  0.42

In [0]:
#get coefficients
pd.Series(linear_reg.coef_, features)

Pclass   -0.195429
Age      -0.006734
Fare      0.000848
dtype: float64

# Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X_train_imputed, y_train)
print('Valid', log_reg.score(X_train_imputed, y_train))

Valid 0.6901197604790419


In [0]:
#The predictions look like this
log_reg.predict(X_train_imputed)

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [0]:
log_reg.predict_prob(X_train_imputed)

AttributeError: ignored

In [0]:
log_reg.predict()

TypeError: ignored

In [0]:
log_reg.coef_

array([[-0.84573613, -0.03196344,  0.0049728 ]])

In [0]:
def sigmoid(x):
  return 1/ (1+np.e**(-x))

# New Section

category_encorders one hot one hot encoder
sklearn impute simpleimputer
sklearn prepossing standard scaler
sklearn linear_model LogisticRegressionCv

In [0]:
import category_encoders as ce
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegressionCV
from sklearn.preprocessing import StandardScaler

target = 'Survived'
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
XX_train = split_train[features]
yy_train=split_train[target]
XX_val = split_val[features]
yy_val = split_val[target]

encoder = ce.OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(XX_train)
X_val_encoded = encoder.transform(XX_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_encoded = encoder.transform(XX_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)


In [0]:
model=LogisticRegressionCV(cv=5,n_jobs=-1, random_state=42)
model.fit(X_train_scaled, yy_train)
model.score(X_val_scaled, yy_val)

0.8071748878923767

In [0]:
XX_val