<a href="https://colab.research.google.com/github/DAVIDnHANG/DS-Unit-2-Regression-Classification/blob/master/module1/Unit2_RegressionClassification_ipynb_TurnIN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

estimate, y_pred, , coefficient

1) choosing between restrictive method instead of a very flexible approach?
   a) restritive model
      1)Interested in inference, very easy ot understand relationship of y from $X_1, ... X_n$
   b) flexible model
      1) harder to undersatnd relationship

1) $F(X) = B_0 + B_1X_1 + ... + B_p X_p$

2) estimates these "coefficient"
 $B_0, B_1,  ... B_n$

3) B_0 is Y when all  value $X_0 ... X_n$ =0


coef_ - this number represents if this is the best fit?
midel_intercept_ - y intercept

#for multiple coeffient, am i usppose to have nire coefficient?

In [3]:
import os, sys
goCoLab = 'google.colab' in sys.modules

# If you're in Colab...
if goCoLab:
    # Pull files from Github repo
   !get init .
   !get remote add origin
   !get pull origin master
    
    # Install required python packages
   !pip install -r requirements.txt
    
    # Change into directory for module
   os.chdir('module1')

/bin/bash: get: command not found
/bin/bash: get: command not found
/bin/bash: get: command not found
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'


FileNotFoundError: ignored

In [9]:
import sys, os
goCoLab = 'google.colab' in sys.modules

if goCoLab:
  os.chdir('/content')
  !git init .
  !git remote add orgin https://github.com/DAVIDnHANG/DS-Unit-2-Regression-Classification.git
  !git pull origin master
  !pip install -r requirements.txt

  os.chdir('module1')

Reinitialized existing Git repository in /content/.git/
fatal: remote orgin already exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'


FileNotFoundError: ignored

In [0]:

# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
#read NYC apartment rental listing data
import pandas as pd
#df = pd.read_csv('../data/apartments/renthop-nyc.csv')
df = pd.read_csv('https://raw.githubusercontent.com/DAVIDnHANG/DS-Unit-2-Regression-Classification/master/data/apartments/renthop-nyc.csv' , na_values='-')
assert df.shape == (49352,34)

In [0]:
#extreme price 1375 <= x <= 15500
#extreme latitude 40.57<= y <= 40.99
#extreme longitude -74.1 <=z<=73.38

df = df[     (df['price'] >= 1375) &(df['price'] <= 15500) &
             (df['latitude'] >= 40.57) & (df['latitude'] < 40.99) &
            (df['longitude'] >= -74.1 ) & (df['longitude'] <= -73.38)  
        ] 


In [0]:
df.head(2)

In [0]:
# 1. Import the appropriate estimator class from Scikit-Learn
from sklearn.linear_model import LinearRegression
#2instanteous the linear regression model
model = LinearRegression()
#3 create the feature, target variables for linearRegression
features = ['bathrooms']
target = ['price']
X_train = df[features]
y_train = df[target]
#4fit the model
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
#X always a matrix[[]]
bathrooms = 2
#we are testing our guessing with the train model.
X_test = [[bathrooms], [bathrooms+1]]
model.predict(X_test)
y_pred = model.predict(X_test)
print(f'Predicted price for {X_test} sq ft Tribeca condo:\n' + str(y_pred))

Predicted price for [[2], [3]] sq ft Tribeca condo:
[[5633.65332568]
 [8207.02772077]]


In [0]:
#make a function for predict
def predict(var_feature):
  #Matrix....
  y_pred = model.predict([[var_feature]])
  # y_pred will return $B_0, B_1, ... B_n$ 
  estimate = y_pred[0] #B_0, B_1 ... Y= B_0 such that X_1,... X_n =0 #y_pred[0] is an index pointing at index 0.
  #the coeff are $B_0, B_1, ... B_n in B_0 + bathroom(B_1) + ... +$  
  coefficient = model.coef_[0]
#  result = f'${estimate:,.0f} estimated price for {var_feature:,.0f} asd.'
#  explanation = f'In this linear regression, each additional square foot adds ${coefficient:,.0f}'
  result =  'price for' , var_feature, 'bathroom'
  explanation = f'is, ${coefficient}'
  return result, explanation, y_pred
predict(2)

(('price for', 2, 'bathroom'),
 'is, $[2573.37439508]',
 array([[5633.65332568]]))

In [0]:
#linear regression on two catagories data
#use the instanteous value model
reg = LinearRegression()
#target and feature for two+ variables
features = ['bathrooms','bedrooms']
target = ['price']
X_train = df[features]
Y_train = df[target]

#fit
reg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
#instanteous for two feature regression

bathrooms_two = 2
bedrooms_two = 3
X_test_two = [[bathrooms_two, bedrooms_two]]
y_pred_two = reg.predict(X_test_two)

print(y_pred_two, X_test_two)

[[5818.43891708]] [[2, 3]]


In [0]:
#make a predict function for X_1, X_2 , B_1,B_2, B_0
def predictMulti(guess_one):
  #using reg as instanteous linear regression
  #grab predictor, estimator, and error
  y_pred_f = reg.predict([guess_one]) ###again double brackets means this is a matrix. pred = X_1, X_2
  estimator_f = y_pred[0]  #this is the B_0
  coeff_f = reg.coef_ #for each additionally foot, X corresponding to coeff_f, it cost this much more.
  #
  s2 = "for", guess_one[0], "bathroom and", guess_one[1], "bedroom it will cost you", estimator_f[0]
  s1= "cost you this", coeff_f, "much more." 
  #print answer
  return s2 + s1

In [0]:
predictMulti([2,3])

('for',
 2,
 'bathroom and',
 3,
 'bedroom it will cost you',
 5633.653325684267,
 'cost you this',
 array([[2099.14867224,  385.08418275]]),
 'much more.')

In [0]:
#let draw a graph
import plotly.express as px
px.scatter(df,x='price',y='bedrooms')

In [0]:
df.head(66)

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0         1.5         3  ...                 0                    0
1         1.0         2  ...                 0                    0
2         1.0         1  ...                 0                    0
3         1.0         1  ...                 0                    0
4         1.0         4  ...                 0                    0
5         2.0         4  ...                 0                    0
6         1.0         2  ...                 0                    0
7         2.0         1  ...                 0                    0
8         1.0         1  ...                 0                    0
9         2.0         4  ...                 0                    0
10        1.0         0  ...                 0                    0
11        1.0         1  ...                 0                    0
12        1.0         2  ...                 0                    0
13        2.0         2  ...                 0                    0
14        1.0         1  ...                 0                    0
15        1.0         0  ...                 0                    0
16        1.0         2  ...                 0                    0
17        1.0         1  ...                 0                    0
18        1.0         4  ...                 0                    0
19        1.0         1  ...                 0                    0
20        1.0         3  ...                 0                    0
21        1.0         2  ...                 0                    0
22        1.0         1  ...                 0                    0
23        1.0         1  ...                 0                    0
24        2.0         4  ...                 0                    0
25        3.5         4  ...                 0                    0
26        1.0         1  ...                 0                    0
27        1.0         1  ...                 0                    0
29        2.0         2  ...                 0                    0
30        1.0         0  ...                 0                    0
..        ...       ...  ...               ...                  ...
38        2.0         2  ...                 0                    0
39        1.0         0  ...                 0                    0
40        1.0         3  ...                 0                    0
41        3.0         4  ...                 1                    0
42        1.0         0  ...                 0                    0
43        1.0         0  ...                 0                    0
44        1.0         1  ...                 0                    0
45        1.0         1  ...                 0                    0
46        1.0         0  ...                 0                    0
47        1.0         2  ...                 0                    0
48        1.0         1  ...                 0                    0
49        1.0         2  ...                 0                    1
50        1.0         1  ...                 0                    0
51        1.0         1  ...                 0                    0
52        1.0         0  ...                 0                    0
53        1.0         1  ...                 0                    0
54        1.0         0  ...                 0                    0
55        2.0         2  ...                 0                    0
56        1.0         2  ...                 0                    0
57        1.0         0  ...                 0                    0
58        1.0         3  ...                 0                    1
59        1.0         1  ...                 0                    0
60        1.0         2  ...                 0                    0
61        1.0         1  ...                 0                    0
62        1.0         0  ...                 0                    0
63        1.0         2  ...                 0                    0
64        1.0         1  ...                 0              

In [13]:
df.head(2)

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0

[2 rows x 34 columns]

In [79]:
#import linearreg
df.fillna(0)
from sklearn.linear_model import LinearRegression
import sklearn
#instanteous import with a variable
LinReg_three = LinearRegression()
#create train, fit model
features = ['bedrooms' , 'bathrooms', 'garden_patio', 'high_speed_internet', 'latitude', 'longitude']
X_train_three = df[features]
y_pred_three = df['price'] 
#now we need to fit
LinReg_three.fit(X_train_three,y_pred_three)
print(df.isna().sum())




bathrooms                  0
bedrooms                   0
created                    0
description             1425
display_address          133
latitude                   0
longitude                  0
price                      0
street_address            10
interest_level             0
elevator                   0
cats_allowed               0
hardwood_floors            0
dogs_allowed               0
doorman                    0
dishwasher                 0
no_fee                     0
laundry_in_building        0
fitness_center             0
pre-war                    0
laundry_in_unit            0
roof_deck                  0
outdoor_space              0
dining_room                0
high_speed_internet        0
balcony                    0
swimming_pool              0
new_construction           0
terrace                    0
exclusive                  0
loft                       0
garden_patio               0
wheelchair_access          0
common_outdoor_space       0
dtype: int64


In [68]:
# let grab the intercept and coef_ 
print(LinReg_three.intercept_)
print(LinReg_three.coef_)

-1297014.598444411
[   423.45598963   2022.98836063    230.32049771    -52.05042615
   1988.54772103 -16444.8741175 ]


In [69]:
coeff_df = pd.DataFrame(LinReg_three.coef_, X_train_three.columns, columns = ['Coefficient'])
coeff_df

Coefficient
bedrooms               423.455990
bathrooms             2022.988361
garden_patio           230.320498
high_speed_internet    -52.050426
latitude              1988.547721
longitude           -16444.874118

In [0]:
X_train_three, X_test_three, y_train_three, y_test_three = sklearn.model_selection.train_test_split(X_train_three,y_pred_three, test_size=.2, random_state=0)

In [83]:
y_pred_t = LinReg_three.predict(X_test_three)
df_three = pd.DataFrame({'Actual':y_test_three, 'Predicted': y_pred_t})
df_three.head(55)


Actual    Predicted
2319     1900  2390.952373
10283    2350  2244.549367
44406    2499  2869.183070
13197   14500  6220.546855
21517    5750  3217.808608
22483    2800  3104.812500
28463    3700  3329.151561
48387    4921  5413.824423
26848    2100  5707.507230
28422    5000  3130.856052
40653    3400  3295.584027
41440    2798  2883.585747
40765    2750  3064.426995
2841     2650  3649.406079
224      2600  2896.436828
24620    5400  6013.919367
38974    3600  3560.000772
9493     4309  3281.464952
32228   10000  6930.987451
2405     3830  5913.134378
13185    2900  3046.693886
20096    3160  5250.956571
5754     5000  6238.993123
2011     2895  3558.437892
11260    2300  2535.209483
6682     3150  2786.519275
24212    1675  2530.676984
22781   11000  5838.149402
30109    2250  2373.743564
1892     1780  1111.785966
29889    1600  2227.482793
7495     2800  2471.241845
11129    2295  3039.039426
8096     5295  3925.422653
15403    4790  3203.561737
38203    3300  2533.512962
18542    1600  2321.095534
33050    2275  3075.937831
16730    3500  3176.053284
26543    1850  2621.833721
7494     5717  6037.952910
30238    3862  3354.723834
30414    3600  3560.000772
5554     2591  2915.772968
8444     4390  3139.192863
20234    5415  3135.903888
37239    3573  4342.221406
44476    3615  3124.000560
8152     2095  2355.821573
10332    6495  6000.489451
19684    2500  2990.370501
16631    2495  2726.739728
43784    2538  2377.092611
36078    2200  2589.915429
19638    2695  3156.681223

In [86]:
import plotly.express as px
px.scatter(df_three, x = 'Actual', y ='Predicted')