<a href="https://colab.research.google.com/github/DAVIDnHANG/DS-Unit-2-Regression-Classification/blob/master/module1/Unit2_RegressionClassification_ipynb_TurnIN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) choosing between restrictive method instead of a very flexible approach?
   a) restritive model
      1)Interested in inference, very easy ot understand relationship of y from $X_1, ... X_n$
   b) flexible model
      1) harder to undersatnd relationship

1) $F(X) = B_0 + B_1X_1 + ... + B_p X_p$

2) estimates these "coefficient"
 $B_0, B_1,  ... B_n$

3) B_0 is Y when all  value $X_0 ... X_n$ =0


In [0]:
import os, sys
goCoLab = 'google.colab' in sys.modules

# If you're in Colab...
if goCoLab:
    # Pull files from Github repo
   !get init .
   !get remote add origin
   !get pull origin master
    
    # Install required python packages
   !pip install -r requirements.txt
    
    # Change into directory for module
   os.chdir('module1')

In [0]:
import sys, os
goCoLab = 'google.colab' in sys.modules

if goCoLab:
  os.chdir('/content')
  !git init .
  !git remote add orgin https://github.com/LambdaSchool/DS-Unit-Regression-Classification.git
  !git pull origin master
  !pip install -r requirements.txt

  os.chdir('module1')

Reinitialized existing Git repository in /content/.git/
fatal: remote orgin already exists.
From https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification
 * branch            master     -> FETCH_HEAD
Already up to date.


In [0]:

# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
#read NYC apartment rental listing data
import pandas as pd
df = pd.read_csv('../data/apartments/renthop-nyc.csv')
assert df.shape == (49352,34)

In [0]:
#extreme price 1375 <= x <= 15500
#extreme latitude 40.57<= y <= 40.99
#extreme longitude -74.1 <=z<=73.38

df = df[     (df['price'] >= 1375) &(df['price'] <= 15500) &
             (df['latitude'] >= 40.57) & (df['latitude'] < 40.99) &
            (df['longitude'] >= -74.1 ) & (df['longitude'] <= -73.38)  
        ] 


In [0]:
df.head(2)

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0

[2 rows x 34 columns]

In [0]:
# 1. Import the appropriate estimator class from Scikit-Learn
from sklearn.linear_model import LinearRegression
#2instanteous the linear regression model
model = LinearRegression()
#3 create the feature, target variables for linearRegression
features = ['bathrooms']
target = ['price']
X_train = df[features]
y_train = df[target]
#4fit the model
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
#X always a matrix[[]]
bathrooms = 2
#we are testing our guessing with the train model.
X_test = [[bathrooms], [bathrooms+1]]
model.predict(X_test)
y_pred = model.predict(X_test)
print(f'Predicted price for {X_test} sq ft Tribeca condo:\n' + str(y_pred))

Predicted price for [[2], [3]] sq ft Tribeca condo:
[[5633.65332568]
 [8207.02772077]]


In [0]:
#make a function for predict
def predict(var_feature):
  #Matrix....
  y_pred = model.predict([[var_feature]])
  # y_pred will return $B_0, B_1, ... B_n$ 
  estimate = y_pred[0] #B_0, B_1 ... Y= B_0 such that X_1,... X_n =0 #y_pred[0] is an index pointing at index 0.
  #the coeff are $B_0, B_1, ... B_n in B_0 + bathroom(B_1) + ... +$  
  coefficient = model.coef_[0]
#  result = f'${estimate:,.0f} estimated price for {var_feature:,.0f} asd.'
#  explanation = f'In this linear regression, each additional square foot adds ${coefficient:,.0f}'
  result =  'price for' , var_feature, 'bathroom'
  explanation = f'is, ${coefficient}'
  return result, explanation
predict(2)

(('price for', 2, 'bathroom'), 'is, $[2573.37439508]')

In [0]:
#linear regression on two catagories data
#use the instanteous value model
reg = LinearRegression()
#target and feature for two+ variables
features = ['bathrooms','bedrooms']
target = ['price']
X_train = df[features]
Y_train = df[target]

#fit
reg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
#instanteous for two feature regression

bathrooms_two = 2
bedrooms_two = 3
X_test_two = [[bathrooms_two, bedrooms_two]]
y_pred_two = reg.predict(X_test_two)

print(y_pred_two, X_test_two)

[[5818.43891708]] [[2, 3]]


In [0]:
#make a predict function for X_1, X_2 , B_1,B_2, B_0
def predictMulti(guess_one):
  #using reg as instanteous linear regression
  #grab predictor, estimator, and error
  y_pred_f = reg.predict([guess_one]) ###again double brackets means this is a matrix. pred = X_1, X_2
  estimator_f = y_pred[0]  #this is the B_0
  coeff_f = reg.coef_[0] #this is the 
  #print answer
  return y_pred_f, estimator_f, coeff_f

In [0]:
predictMulti([2,3])

(array([[5818.43891708]]),
 array([5818.43891708]),
 array([2099.14867224,  385.08418275]))